php54:
  image: php:5.4-apache
  volumes:
  - ./:/var/www/html/


php55:
  image: php:5.5-apache
  volumes:
  - ./:/var/www/html/


php56:
  image: php:5.6-apache
  volumes:
  - ./:/var/www/html/


php7:
  image: php:7-apache
  volumes:
  - ./index.php:/var/www/html/index.php


#lb:
#  image: tutum/haproxy
#  links:
#   - php54
#   - php55
#   - php56
#   - php7
#  ports:
#   - "8080:80"
#  environment:
#   - BALANCE=roundrobin
lb:
    image: dockercloud/haproxy
    links:
      - php54
      - php55
      - php56
      - php7
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    ports:
      - 80:80