version: '2'
services:
    web:
        image: wordpress
        environment:
            - WORDPRESS_DB_PASSWORD=password
            - WORDPRESS_DB_HOST=mysql
        ports:
            - "80:80"
        links:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=wordpress